#
# Vivado (TM) v2013.4 (64-bit)
#
# TE0720-01_Base_Vivado-2013.4.tcl: Tcl script for re-creating project 'base'
#
# Generated by Vivado on Sun Feb 16 15:20:49 +0100 2014
# IP Build 208076 on Mon Dec  2 12:38:17 MST 2013
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (TE0720-01_Base_Vivado-2013.4.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' variable setting below at the start of the script)
#
#    "B:/Temporary/TE0720-01_Base_Vivado-2013.4/base.srcs/sources_1/bd/zynq_sys/zynq_sys.bd"
#    "B:/Temporary/TE0720-01_Base_Vivado-2013.4/base.srcs/sources_1/bd/zynq_sys/hdl/zynq_sys_wrapper.vhd"
#    "B:/Temporary/TE0720-01_Base_Vivado-2013.4/src/top.vhd"
#    "B:/Temporary/TE0720-01_Base_Vivado-2013.4/base.srcs/sources_1/imports/TE0701-Vivado/component.xml"
#    "B:/Temporary/TE0720-01_Base_Vivado-2013.4/base.srcs/sources_1/bd/zynq_sys/ip/zynq_sys_processing_system7_1_0/zynq_sys_processing_system7_1_0.upgrade_log"
#    "B:/Temporary/TE0720-01_Base_Vivado-2013.4/src/constraints/TE0701-03.xdc"
#    "B:/Temporary/TE0720-01_Base_Vivado-2013.4/src/constraints/TE0720-01.xdc"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the original project directory path for adding/importing sources in the new project
set orig_proj_dir [pwd]

# Create project
create_project base ./base

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects base]
set_property "part" "xc7z020clg484-2" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Add files to 'sources_1' fileset
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$orig_proj_dir/base.srcs/sources_1/bd/zynq_sys/zynq_sys.bd"]"\
 "[file normalize "$orig_proj_dir/base.srcs/sources_1/bd/zynq_sys/hdl/zynq_sys_wrapper.vhd"]"\
 "[file normalize "$orig_proj_dir/src/top.vhd"]"\
 "[file normalize "$orig_proj_dir/base.srcs/sources_1/imports/TE0701-Vivado/component.xml"]"\
 "[file normalize "$orig_proj_dir/base.srcs/sources_1/bd/zynq_sys/ip/zynq_sys_processing_system7_1_0/zynq_sys_processing_system7_1_0.upgrade_log"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 "./base.srcs/sources_1/bd/zynq_sys/zynq_sys.bd"\
 "./base.srcs/sources_1/bd/zynq_sys/hdl/zynq_sys_wrapper.vhd"\
 "./src/top.vhd"\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "hdl/zynq_sys_wrapper.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "src/top.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "top" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Add files to 'constrs_1' fileset
set obj [get_filesets constrs_1]
set files [list \
 "[file normalize "$orig_proj_dir/src/constraints/TE0701-03.xdc"]"\
 "[file normalize "$orig_proj_dir/src/constraints/TE0720-01.xdc"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 "./src/constraints/TE0701-03.xdc"\
 "./src/constraints/TE0720-01.xdc"\
]
set imported_files [import_files -fileset constrs_1 $files]

# Set 'constrs_1' fileset file properties for remote files
# None

# Set 'constrs_1' fileset file properties for local files
set file "constraints/TE0701-03.xdc"
set file_obj [get_files -of_objects constrs_1 [list "*$file"]]
set_property "file_type" "XDC" $file_obj

set file "constraints/TE0720-01.xdc"
set file_obj [get_files -of_objects constrs_1 [list "*$file"]]
set_property "file_type" "XDC" $file_obj


# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "target_constrs_file" "./src/constraints/TE0701-03.xdc" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets sim_1] ""]} {
  create_fileset -simset sim_1
}

# Add files to 'sim_1' fileset
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "top" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs synth_1] ""]} {
  create_run -name synth_1 -part xc7z020clg484-2 -flow {Vivado Synthesis 2013} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
}
set obj [get_runs synth_1]
set_property "needs_refresh" "1" $obj
set_property "part" "xc7z020clg484-2" $obj

# Create 'impl_1' run (if not found)
if {[string equal [get_runs impl_1] ""]} {
  create_run -name impl_1 -part xc7z020clg484-2 -flow {Vivado Implementation 2013} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
}
set obj [get_runs impl_1]
set_property "needs_refresh" "1" $obj
set_property "part" "xc7z020clg484-2" $obj


puts "INFO: Project created:base"
