
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.4 EDK_2013.4.20131205
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xadcps.h"

/*
* The configuration table for devices
*/

XAdcPs_Config XAdcPs_ConfigTable[] =
{
	{
		XPAR_PS7_XADC_0_DEVICE_ID,
		XPAR_PS7_XADC_0_BASEADDR
	}
};


